version: 2

updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: daily
      time: "08:00"
      timezone: "Asia/Yekaterinburg"
    commit-message:
      prefix: "fix(deps)"
      prefix-development: "fix(deps)"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
      time: "08:00"
      timezone: "Asia/Yekaterinburg"
    commit-message:
      prefix: "ci(actions)"

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: daily
      time: "08:00"
      timezone: "Asia/Yekaterinburg"
    commit-message:
      prefix: "ci(docker)"
