changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - octocat
  categories:
    - title: Dependencies update 🕗
      labels:
        - dependencies
        - build
    - title: Bug fixes 🐛
      labels:
        - fix
    - title: Features ✨
      labels:
        - feature
    - title: Documentation 📚
      labels:
        - docs
    - title: Style 🎨
      labels:
        - style
    - title: Refactoring 🛠
      labels:
        - refactoring
    - title: Continuous Integration 🤖
      labels:
        - ci
    - title: Reverts 🗑
      labels:
        - revert
    - title: Performance 🚀
      labels:
        - perfomance
    - title: Tests 🚨
      labels:
        - test
    - title: Chores ♻️
      labels:
        - chore
    - title: Breaking Changes 💥
      labels:
        - breaking
    - title: Other Changes 📝
      labels:
        - '*'
