exclude: "(alembic/)"
repos:
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.4.1"
    hooks:
      - id: mypy
        args: [--ignore-missing-imports, --disallow-untyped-defs]
        additional_dependencies:
          - "pyjwt==2.7.0"
          - "types-python-slugify==8.0.0.3"
          - "pydantic==2.1.1"
          - "types-aiofiles==23.2.0.0"
  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
        language_version: python3.10
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v2.3.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args:
          - feat
          - fix
          - docs
          - style
          - refactor
          - ci
          - revert
          - perf
          - test
          - chore
  - repo: https://github.com/python-poetry/poetry
    rev: "1.4.1"
    hooks:
      - id: poetry-check
      - id: poetry-lock
        args: ["--no-update"]
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    # Ruff version.
    rev: "v0.0.287"
    hooks:
      - id: ruff
        args: [--fix]
