exclude: "(alembic/)"
repos:
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.1.1'
    hooks:
      - id: mypy
        args: [ --ignore-missing-imports, --disallow-untyped-defs ]
        additional_dependencies: [ pyjwt==2.0.0,  types-python-slugify==8.0.0.2]
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v2.1.1
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: 
         - feat
         - fix
         - docs
         - style
         - refactor
         - ci
         - revert
         - perf
         - test
         - chore
  - repo: https://github.com/python-poetry/poetry
    rev: '1.4.1'
    hooks:
      - id: poetry-check
      - id: poetry-lock
        args: ["--no-update"]
  - repo: https://github.com/charliermarsh/ruff-pre-commit
  # Ruff version.
    rev: 'v0.0.260'
    hooks:
      - id: ruff