exclude: "(alembic/)"
repos:
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.13.0"
    hooks:
      - id: mypy
        args: [--ignore-missing-imports, --disallow-untyped-defs]
        additional_dependencies:
          - "types-python-slugify==8.0.0.3"
          - "pydantic==2.10.1"
          - "types-aiofiles==24.1.0.20240626"
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.6.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args:
          - feat
          - fix
          - docs
          - style
          - refactor
          - ci
          - revert
          - perf
          - test
          - chore
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    # Ruff version.
    rev: "v0.8.1"
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
