runner:
  flake8:
    cmd: poetry run flake8 .
    level: error
    format: flake8
  black:
    cmd: poetry run black --check .
    level: error
    format: black
  isort:
    cmd: poetry run isort --check .
    level: error
    format: isort
  mypy:
    cmd: poetry run mypy .
    level: warning
    format: mypy