runner:
  ruff:
    cmd: poetry run ruff check .
    level: error
    errorformat:
      - "%f:%l:%c: %m"
  ruff-format:
    cmd: poetry run ruff format --check .
    level: error
    format: diff
  mypy:
    cmd: poetry run mypy .
    level: error
    format: mypy
