runner:
  ruff:
    cmd: poetry run ruff check .
    level: error
    errorformat:
      - "%f:%l:%c: %m"
  mypy:
    cmd: poetry run mypy .
    level: error
    format: mypy
  black:
    cmd: poetry run black --check .
    level: error
    format: black