services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./deployment/postgresql/initdb:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    volumes:
      - minio:/data
    ports:
      - "9000:9000"
      - "9001:9001"

  meilisearch:
    image: getmeili/meilisearch:v1.23
    volumes:
      - meili:/meili_data
    ports:
      - "7700:7700"

volumes:
  postgres:
  minio:
  meili:
