services:
  postgres:
    image: postgres:14.5
    environment:
      POSTGRES_PASSWORD: postgrespw
      POSTGRES_USER: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  nats:
    image: nats:2.9-alpine
    ports:
      - "4222:4222"
      - "8222:8222"
    command: ["--http_port", "8222", "-js", "-sd", "/data/jetstream"]
    volumes:
      - nats:/data/jetstream:rw

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    volumes:
      - minio:/data
    ports:
      - "9000:9000"
      - "9001:9001"

  meili:
    image: getmeili/meilisearch:v1.2.0
    ports:
      - "7700:7700"
    volumes:
      - meili:/meili_data

volumes:
  postgres:
  minio:
  meili:
  nats:
