FROM python:3.9-alpine
ENV PYTHONUNBUFFERED 1

RUN mkdir /api
WORKDIR /api

COPY requirements* ./
RUN \
    apk add --no-cache postgresql-libs jpeg-dev zlib-dev && \
    apk add --no-cache --virtual .build-deps gcc musl-dev postgresql-dev && \
    pip install --no-cache-dir -r requirements.txt -r requirements-dev.txt && \
    apk --purge del .build-deps

ADD . /api/

ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.7.3/wait /wait
RUN chmod +x /wait