"""Add posts table

Revision ID: 0eb3f6853123
Revises: 6819601080a6
Create Date: 2020-02-20 17:48:06.790007

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '0eb3f6853123'
down_revision = '6819601080a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'posts',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(), nullable=False),
        sa.Column('annotation', sa.String(), nullable=True),
        sa.Column('text', sa.Text(), nullable=False),
        sa.Column('slug', sa.String(), nullable=False),
        sa.Column('published_at', sa.DateTime(), nullable=False),
        sa.Column('thumbnail', sa.String(), nullable=True),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('slug'),
        sa.UniqueConstraint('title')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('posts')
    # ### end Alembic commands ###
