"""Added cascading video deletion when deleting a channel

Revision ID: 1001e80b684b
Revises: 289a1dbe60a5
Create Date: 2020-06-16 10:52:41.988300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1001e80b684b'
down_revision = '289a1dbe60a5'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('videos_channel_id_fkey', 'videos', type_='foreignkey')
    op.create_foreign_key(None, 'videos', 'channels', ['channel_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'videos', type_='foreignkey')
    op.create_foreign_key('videos_channel_id_fkey', 'videos', 'channels', ['channel_id'], ['id'])
    # ### end Alembic commands ###
