"""Added group members culumn to djs table

Revision ID: 1a3352bb0537
Revises: 3a0190da28b1
Create Date: 2021-03-11 12:35:06.316379

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "1a3352bb0537"
down_revision = "3a0190da28b1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "djs",
        sa.Column("group_members", sa.ARRAY(sa.String()), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("djs", "group_members")
    # ### end Alembic commands ###
