"""change columns of tokens table

Revision ID: 2450624e90ee
Revises: 3e42d8173db1
Create Date: 2023-04-12 16:25:50.652214

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "2450624e90ee"
down_revision = "3e42d8173db1"
branch_labels = None
depends_on = None


def upgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users_tokens",
        sa.Column("expired_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "users_tokens",
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.drop_constraint(
        "users_tokens_token_key",
        "users_tokens",
        type_="unique",
    )
    op.drop_column("users_tokens", "token")
    # ### end Alembic commands ###


def downgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users_tokens",
        sa.Column(
            "token",
            sa.VARCHAR(length=64),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.create_unique_constraint(
        "users_tokens_token_key",
        "users_tokens",
        ["token"],
    )
    op.drop_column("users_tokens", "revoked_at")
    op.drop_column("users_tokens", "expired_at")
    # ### end Alembic commands ###
