"""Add craeted at column to liked videos

Revision ID: 289a1dbe60a5
Revises: c8b2be2c0ece
Create Date: 2020-05-12 12:30:49.587670

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '289a1dbe60a5'
down_revision = 'c8b2be2c0ece'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('liked_videos',
                  sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('liked_videos', 'created_at')
    # ### end Alembic commands ###
