"""add user videos id generation

Revision ID: 31bf219b29b4
Revises: 010420cef18f
Create Date: 2023-08-27 18:38:22.313278

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "31bf219b29b4"
down_revision = "010420cef18f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "liked_videos",
        "id",
        server_default=sa.text("uuid_generate_v4()"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "liked_videos",
        "id",
        server_default=None,
    )
    # ### end Alembic commands ###
