"""Add duration column to videos

Revision ID: 3d756e8f5eea
Revises: cf908b3cb65b
Create Date: 2019-12-02 16:06:21.202401

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "3d756e8f5eea"
down_revision = "cf908b3cb65b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("videos", sa.Column("duration", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("videos", "duration")
    # ### end Alembic commands ###
