"""Added cascade delete and update for groups_members table

Revision ID: 68877806bd50
Revises: 814e5913658f
Create Date: 2021-03-17 13:19:42.552551

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = '68877806bd50'
down_revision = '814e5913658f'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('groups_members_group_id_fkey', 'groups_members', type_='foreignkey')
    op.drop_constraint('groups_members_dj_id_fkey', 'groups_members', type_='foreignkey')
    op.create_foreign_key(None, 'groups_members', 'djs', ['group_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'groups_members', 'djs', ['dj_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'groups_members', type_='foreignkey')
    op.drop_constraint(None, 'groups_members', type_='foreignkey')
    op.create_foreign_key('groups_members_dj_id_fkey', 'groups_members', 'djs', ['dj_id'], ['id'])
    op.create_foreign_key('groups_members_group_id_fkey', 'groups_members', 'djs', ['group_id'], ['id'])
    # ### end Alembic commands ###
