"""Add deleted column to videos

Revision ID: 68d958550cc4
Revises: e548b42691f0
Create Date: 2020-01-16 16:44:53.367148

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '68d958550cc4'
down_revision = 'e548b42691f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'videos',
        sa.Column(
            'deleted',
            sa.Boolean(),
            nullable=True,
            server_default=sa.schema.DefaultClause("0")
        )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'deleted')
    # ### end Alembic commands ###
