"""add delete type

Revision ID: 7e3bdedfd323
Revises: abc41cb413ee
Create Date: 2025-07-08 22:48:51.593996

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "7e3bdedfd323"
down_revision = "abc41cb413ee"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum("PERMANENT", "TEMPORARY", name="deletetype").create(op.get_bind())
    op.add_column(
        "videos",
        sa.Column(
            "delete_type",
            sa.Enum(
                "PERMANENT",
                "TEMPORARY",
                name="deletetype",
            ),
            nullable=True,
        ),
    )
    op.alter_column(
        "videos",
        "is_blocked_in_russia",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("false"),
    )
    op.execute("UPDATE videos SET delete_type = 'PERMANENT' WHERE deleted = true")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "videos",
        "is_blocked_in_russia",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("false"),
    )
    op.drop_column("videos", "delete_type")
    sa.Enum("PERMANENT", "TEMPORARY", name="deletetype").drop(op.get_bind())
    # ### end Alembic commands ###
