"""Migrate dj arrays to many to many association

Revision ID: 814e5913658f
Revises: 1a3352bb0537
Create Date: 2021-03-12 10:30:29.668701

"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "814e5913658f"
down_revision = "1a3352bb0537"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "groups_members",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("group_id", sa.Integer(), nullable=False),
        sa.Column("dj_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["dj_id"],
            ["djs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["djs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("group_id", "dj_id"),
    )
    op.drop_column("djs", "member_of_groups")
    op.drop_column("djs", "group_members")
    op.add_column(
        "djs",
        sa.Column("is_group", sa.Boolean(), server_default="f"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("djs", "is_group")
    op.add_column(
        "djs",
        sa.Column(
            "group_members",
            postgresql.ARRAY(sa.VARCHAR()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "djs",
        sa.Column(
            "member_of_groups",
            postgresql.ARRAY(sa.VARCHAR()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_table("groups_members")
    # ### end Alembic commands ###
