"""Remove events table

Revision ID: 9ac61fa239aa
Revises: 0eb3f6853123
Create Date: 2020-04-30 16:47:43.829171

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "9ac61fa239aa"
down_revision = "0eb3f6853123"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("videos_event_id_fkey", "videos", type_="foreignkey")
    op.drop_column("videos", "event_id")
    op.drop_table("events")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "events",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("slug", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("image", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name="events_pkey"),
        sa.UniqueConstraint("image", name="events_image_key"),
        sa.UniqueConstraint("name", name="events_name_key"),
        sa.UniqueConstraint("slug", name="events_slug_key"),
    )
    op.add_column(
        "videos",
        sa.Column(
            "event_id", sa.INTEGER(), autoincrement=False, nullable=True,
        ),
    )
    op.create_foreign_key(
        "videos_event_id_fkey", "videos", "events", ["event_id"], ["id"],
    )
    # ### end Alembic commands ###
