"""add_post_edit_history

Revision ID: abc41cb413ee
Revises: a4b5b35350f0
Create Date: 2025-07-19 08:53:24.416639

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "abc41cb413ee"
down_revision = "a4b5b35350f0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "post_edit_history",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("post_id", sa.Integer(), nullable=False),
        sa.Column(
            "edited_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("edited_by", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["post_id"], ["posts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_post_edit_history_post_id"),
        "post_edit_history",
        ["post_id"],
        unique=False,
    )
    op.add_column(
        "posts", sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=True)
    )
    op.add_column("posts", sa.Column("updated_by", sa.Uuid(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("posts", "updated_by")
    op.drop_column("posts", "updated_at")
    op.drop_index(op.f("ix_post_edit_history_post_id"), table_name="post_edit_history")
    op.drop_table("post_edit_history")
    # ### end Alembic commands ###
