"""Rename a column with activation code in users

Revision ID: c8b2be2c0ece
Revises: 0be0ff297f6e
Create Date: 2020-05-06 14:22:58.435941

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "c8b2be2c0ece"
down_revision = "0be0ff297f6e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "activate_code",
        new_column_name="activation_code",
        type_=sa.String(0),
    )
    op.alter_column("users", "recovery_code", type_=sa.String(10))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "activation_code",
        new_column_name="activate_code",
        type_=sa.String,
    )
    op.alter_column("users", "recovery_code", type_=sa.String)
    # ### end Alembic commands ###
