"""Add recovery code column to users table

Revision ID: ee29f266ee74
Revises: 3e6e9e0919e5
Create Date: 2019-12-21 13:59:26.431081

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'ee29f266ee74'
down_revision = '3e6e9e0919e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('recovery_code', sa.String(), nullable=True))
    op.add_column('users', sa.Column('recovery_code_lifetime_end', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'recovery_code_lifetime_end')
    op.drop_column('users', 'recovery_code')
    # ### end Alembic commands ###
