"""add bm25 index to videos table

Revision ID: f7d3db4a8304
Revises: a4b5b35350f0
Create Date: 2025-07-06 15:09:28.548163

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "f7d3db4a8304"
down_revision = "a4b5b35350f0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_search")
    op.alter_column(
        "videos",
        "is_blocked_in_russia",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("false"),
    )
    op.create_index(
        "search_idx",
        "videos",
        [sa.literal_column("id, title, date, is_blocked_in_russia, deleted")],
        unique=False,
        postgresql_using="bm25",
        postgresql_with={"key_field": "id"},
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "search_idx",
        table_name="videos",
        postgresql_using="bm25",
        postgresql_with={"key_field": "id"},
    )
    op.alter_column(
        "videos",
        "is_blocked_in_russia",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("false"),
    )
    op.execute("DROP EXTENSION IF EXISTS pg_search")
    # ### end Alembic commands ###
