"""Add trgm index for full text search

Revision ID: ff571c42ee59
Revises: 04fde0adbc66
Create Date: 2019-12-13 14:54:46.983502

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "ff571c42ee59"
down_revision = "04fde0adbc66"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION pg_trgm;")
    op.create_index(
        "title_idx",
        "videos",
        ["title"],
        unique=False,
        postgresql_ops={"title": "gin_trgm_ops"},
        postgresql_using="gin",
    )
    op.drop_constraint("videos_event_id_fkey", "videos", type_="foreignkey")
    op.create_foreign_key(None, "videos", "events", ["event_id"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "videos", type_="foreignkey")
    op.create_foreign_key(
        "videos_event_id_fkey",
        "videos",
        "events",
        ["channel_id"],
        ["id"],
    )
    op.drop_index("title_idx", table_name="videos")
    op.execute("DROP EXTENSION pg_trgm;")
    # ### end Alembic commands ###
