"""Added livestreams table

Revision ID: ff6fa37c7559
Revises: 6b5432d5749e
Create Date: 2021-01-27 12:54:12.935382

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "ff6fa37c7559"
down_revision = "6b5432d5749e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "livestreams",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=256), nullable=False),
        sa.Column(
            "cancelled",
            sa.Boolean(),
            server_default="f",
            nullable=True,
        ),
        sa.Column("start_time", sa.DateTime(), nullable=True),
        sa.Column("end_time", sa.DateTime(), nullable=True),
        sa.Column("image", sa.String(), nullable=True),
        sa.Column("url", sa.String(length=2083), nullable=True),
        sa.Column("slug", sa.String(), nullable=False),
        sa.Column("genres", sa.ARRAY(sa.String()), nullable=True),
        sa.Column("djs", sa.ARRAY(sa.String()), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_livestreams_slug"),
        "livestreams",
        ["slug"],
        unique=False,
    )
    op.create_index(
        op.f("ix_livestreams_title"),
        "livestreams",
        ["title"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_livestreams_title"), table_name="livestreams")
    op.drop_index(op.f("ix_livestreams_slug"), table_name="livestreams")
    op.drop_table("livestreams")
    # ### end Alembic commands ###
